### ISSUE TITLE
Always list apps that have been auto-deployed

### ISSUE THREAD

**Issue by marksmall** [edina/edina-hubot#10]
The **Update** sub-command returns `All apps deployed to beta`. I believe this means that the command has completed. I made the incorrect assumption that this meant every application had been deployed, if nothing is deployed

```
gortBOT [01:00]  
@rvilla: Auto deploying apps to beta, looking back 1 days

[01:00]  
@rvilla: All apps deployed to beta
```

You can see how this would be confusing. If this is just a message to state the command has completed, we should come up with some more explicit text e.g. `Update Command completed`

**Comment by robertvilla** [comment]
The message displayed by the command has been clarified: https://github.com/edina/edina-hubot/commit/c4192a7c136a7ed09f1037c68c2e7e1b0ce2418c
