### ISSUE TITLE
deploys of artifacts that don't exist report success

### ISSUE THREAD

**Issue by marksmall** [edina/edina-hubot#11]
We built a release of the Digimap Interface on Sept 1st (https://geodev.edina.ac.uk/jenkins/job/dm-maven-release/197/console), with failed. We then used GORT to deploy that release to a number of our machines. GORT responded with a success message

https://teamedina.slack.com/archives/digimap-developers/p1472731283000116

We should look at making it more robust so this situation can't occur again.

**Comment by robertvilla** [comment]
There isn't any easy way (that I know of) to communicate the result of a jenkins build back to gort. Gort could kick of a build as it does now and then poll the state of Jenkins, but this seems over complicated and brittle. 

One possible alternative: 
* we change gort to say that it's starting off a job and might fail, e.g. "Starting deploy <artifactID> v<version> to <site>", or "Starting release of <artifactId> v<version>".
* Use the Jenkins slack plugin to report back the end state of the job. We already get slack notifications of deploys, we can add a notification for releases as well.
